language: go
go:
  - 1.2
services:
  - redis-server
install:
  - go get github.com/go-martini/martini
  - go get github.com/fzzy/radix/redis
  - go get gopkg.in/yaml.v1
script:
  - go test -v github.com/praekelt/unicore_network/...
